name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

